python fisher.py Y1 3x2pt shear_calibration
python fisher.py Y1 3x2pt mean_photo-z
python fisher.py Y1 3x2pt sigma_photo-z
python fisher.py Y1 shear_shear shear_calibration
python fisher.py Y1 shear_shear mean_photo-z
python fisher.py Y1 shear_shear sigma_photo-z
python fisher.py Y1 pos_pos mean_photo-z
python fisher.py Y1 pos_pos sigma_photo-z
python fisher.py Y1 clusterN_clusterWL shear_calibration
python fisher.py Y1 clusterN_clusterWL mean_photo-z
python fisher.py Y1 clusterN_clusterWL sigma_photo-z
python fisher.py Y10 3x2pt shear_calibration
python fisher.py Y10 3x2pt mean_photo-z
python fisher.py Y10 3x2pt sigma_photo-z
python fisher.py Y10 shear_shear shear_calibration
python fisher.py Y10 shear_shear mean_photo-z
python fisher.py Y10 shear_shear sigma_photo-z
python fisher.py Y10 pos_pos mean_photo-z
python fisher.py Y10 pos_pos sigma_photo-z
python fisher.py Y10 clusterN_clusterWL shear_calibration
python fisher.py Y10 clusterN_clusterWL mean_photo-z
python fisher.py Y10 clusterN_clusterWL sigma_photo-z
